### ISSUE TITLE
Reply Interaction

### ISSUE THREAD

**Issue by Pqoh** [iZeaoGamer/Discord-bot#1]
How do I reply to an interaction? like in the screenshot for e.g
![Screenshot_20220210-220922_Discord](https://user-images.githubusercontent.com/48698601/153523123-f848211f-2a4e-4507-ab40-0a2b222e5f5f.png)

I tried the following functions, but none of them responded properly: ```Api->createInteractionResponse()``` and ```Api->respondInteractionWithMessage()```
![Screenshot_20220210-222032_Discord](https://user-images.githubusercontent.com/48698601/153523814-5e0c50d1-a918-4784-a564-de813aa4b3e7.png)

**Comment by iZeaoGamer** [comment]
Hi, Can I see the code for the interaction creation?

**Comment by Pqoh** [comment]
> Hi, Can I see the code for the interaction creation?

```
$command = new Command(Command::CHAT_INPUT, "teste", "teste command", true, []);
$option = new Option(Option::STRING, "link", "afbasdgfbads", true);
$command->setOptions([$option]);
$ApiDiscord->createCommand($command)->done();
```

```
public function onInteractionCreated(InteractionCreated $event) : void{
    $interaction = $event->getInteraction();
    $ApiDisocord->respondInteractionWithMessage($interaction, null, "teste2", null, true)->otherwise(function (ApiResolution $resolution) {
        $this->plugin->getLogger()->warning("Failed to delete discord message, '{$resolution->getMessage()}'");
        }, function (ApiRejection $rejection) {
            $this->plugin->getLogger()->warning("Failed to delete discord message, '{$rejection->getMessage()}'");
        });

}
```

**Comment by iZeaoGamer** [comment]
> 

Is there an error during this action via console?

**Comment by iZeaoGamer** [comment]
Closed due to inactivity.
